### ISSUE TITLE
Remove duplicate `oechem.OEMol` in utils `_set_toolkit`

### ISSUE THREAD

**Issue by bannanc** [openforcefield/cmiles#19]
I was looking into utils to understand how `molecule_to_smiles` so I ended up looking at a line in [`_set_toolkit`](https://github.com/openforcefield/cmiles/blob/master/cmiles/utils.py#L513). There are two things, it looks like `ochem.OEMol` is in the list twice, but also `oechem.OEMolBase` is the parent class for `OEMol` and `OEGraphMol` so that should be the only thing you have to check I think.

**Comment by ChayaSt** [comment]
Thanks for catching that. Added the fix with #20
