### ISSUE TITLE
Conda package?

### ISSUE THREAD

**Issue by jchodera** [openforcefield/cmiles#3]
Do we have a conda recipe in omnia for this yet?
https://github.com/omnia-md/conda-recipes

Or is it on conda-forge?

**Comment by dgasmith** [comment]
We could consider making an environment that has exact pinned versions of dependancies. This will not be accepted on Conda-forge, but still quite useful. We could also put a very simple web front-end on cmiles so that people can ping a server and get an anticipated result.

**Comment by jchodera** [comment]
> We could consider making an environment that has exact pinned versions of dependancies. This will not be accepted on Conda-forge, but still quite useful. We could also put a very simple web front-end on cmiles so that people can ping a server and get an anticipated result.

An [`environment.yml`](https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) file is probably the right way to do that, and you can use this in the `Dockerfile`.

**Comment by ChayaSt** [comment]
I see rdkit is on conda-forge now. 
https://anaconda.org/conda-forge/rdkit.

**Comment by dgasmith** [comment]
Oh, that's really great! It would be good to get this on Conda-forge then. I believe the output contains the RDKit version which is good. We might want some kind of marker that indicated if the current RDKit version is "correct" or not as well.

**Comment by mattwthompson** [comment]
I see  #29 is a duplicate, although we did not pin the RDKit version on the `conda-forge` package
